import React from 'react';
import { Industry, CandidateType } from './types';
import { 
    Briefcase, 
    Zap, 
    Globe, 
    ShoppingCart, 
    Cpu, 
    DollarSign, 
    Users,
    PawPrint,
    Bot,
    Stethoscope
} from 'lucide-react';

export const INDUSTRIES = Object.values(Industry);
export const CANDIDATE_TYPES = Object.values(CandidateType);

export const INDUSTRY_ICONS: Record<Industry, React.ReactNode> = {
    [Industry.INTERNET]: <Globe className="w-5 h-5" />,
    [Industry.ECOMMERCE]: <ShoppingCart className="w-5 h-5" />,
    [Industry.FMCG]: <Users className="w-5 h-5" />, 
    [Industry.AI]: <Cpu className="w-5 h-5" />,
    [Industry.NEW_ENERGY]: <Zap className="w-5 h-5" />,
    [Industry.FINANCE]: <DollarSign className="w-5 h-5" />,
    [Industry.CONSULTING]: <Briefcase className="w-5 h-5" />,
    [Industry.PETS]: <PawPrint className="w-5 h-5" />,
    [Industry.ROBOTICS]: <Bot className="w-5 h-5" />,
    [Industry.HEALTHCARE]: <Stethoscope className="w-5 h-5" />,
};

export const COLORS = {
    primary: '#4f46e5', 
    secondary: '#0ea5e9', 
    accent: '#8b5cf6', 
    success: '#10b981', 
    warning: '#f59e0b', 
    danger: '#ef4444', 
    dark: '#0f172a', 
};

export const TRANSLATIONS = {
    CN: {
        title: "MarketPulse 职场风向标",
        subtitle: "实时分析各行业非技术岗位的招聘趋势、新闻及成功策略",
        analysisDate: "分析日期",
        selectIndustry: "选择行业",
        targetAudience: "目标人群",
        generate: "生成报告",
        analyzing: "正在分析...",
        marketSentiment: "市场情绪摘要 & 机会洞察",
        jobChartTitle: "岗位需求量 vs 竞争难度",
        jobChartSubtitle: "招聘热度与竞争激烈的对比 (0-100)",
        volume: "招聘热度",
        difficulty: "竞争难度",
        cityTitle: "招聘热门城市",
        newsTitle: "最新行业资讯",
        readSource: "阅读原文",
        noNews: "暂无相关新闻",
        bestRole: "最佳投递机会",
        successPrediction: "成功率预测",
        bestRoleDesc: "基于当前的供需比，该岗位目前的成功率最高。",
        successProfile: "胜任力模型 & 成功画像",
        impact: "权重",
        successFactor: "成功要素占比",
        idealProfile: "理想候选人画像",
        hardSkills: "硬性技能",
        softSkills: "软性素质",
        expertTip: "专家建议",
        roadmap: "大学四年规划：分阶段投递策略",
        coreFocus: "核心侧重",
        bestRolesTarget: "重点投递岗位",
        why: "推荐理由",
        topCompanies: "名企推荐 & 规模分析",
        marketCap: "市值/估值/规模",
        location: "城市",
        keywords: "核心关键词",
        opportunities: "求职机会点",
        risks: "避坑指南 / 风险提示",
        downloadPDF: "PDF",
        downloadImage: "长图"
    },
    EN: {
        title: "MarketPulse Career Tracker",
        subtitle: "Real-time analysis of non-tech recruitment trends, news, and success strategies.",
        analysisDate: "Analysis Date",
        selectIndustry: "Select Industry",
        targetAudience: "Target Audience",
        generate: "Get Insights",
        analyzing: "Analyzing...",
        marketSentiment: "Market Sentiment & Insights",
        jobChartTitle: "Hiring Volume vs. Competition",
        jobChartSubtitle: "Hiring Volume vs. Competition Difficulty (0-100)",
        volume: "Hiring Volume",
        difficulty: "Competition",
        cityTitle: "Top Hiring Cities",
        newsTitle: "Latest Industry News",
        readSource: "Read Source",
        noNews: "No news available.",
        bestRole: "Best Opportunity",
        successPrediction: "Success Prediction",
        bestRoleDesc: "Based on current volume/difficulty ratio, this role offers the highest probability of success.",
        successProfile: "Success Profile & Skill Analysis",
        impact: "Impact",
        successFactor: "Success Factor Weight",
        idealProfile: "Ideal Candidate Profile",
        hardSkills: "Hard Skills",
        softSkills: "Soft Skills",
        expertTip: "Success Tip",
        roadmap: "Strategic Roadmap: University Year 1-4",
        coreFocus: "Core Focus",
        bestRolesTarget: "Best Roles to Target",
        why: "Why?",
        topCompanies: "Top Hiring Companies by Size",
        marketCap: "Valuation/Scale",
        location: "Location",
        keywords: "Keywords",
        opportunities: "Key Opportunities",
        risks: "Risks & Pitfalls",
        downloadPDF: "PDF",
        downloadImage: "Image"
    }
};